### ISSUE TITLE
Ladies of code rebrand update

### ISSUE THREAD

**Issue by RabeaGleissner** [ladiesofcode/london#23]
![loc_animated_colour](https://cloud.githubusercontent.com/assets/8995723/12703902/58324a9e-c846-11e5-9f8f-49326881efaf.gif)
Hi @iteles 

Just a heads up, I'm planning to sit down at the weekend and update our repo to the new name and maybe write a couple of lines about the name change. I won't update any historical meetup information, probably just the front page Readme file.

I'll raise a PR for you to merge when I'm done...

**Comment by iteles** [comment]
@RabeaGleissner Sounds wonderful, thanks!
