### ISSUE TITLE
Permissions for repos

### ISSUE THREAD

**Issue by iteles** [ladiesofcode/london#24]
Hi @angiemaguire,

@RabeaGleissner and I can't assign issues or add labels to them. Can we please have the relevant permissions as we had in the LWC org (which is why I was able to move the london repo out of LWC and into LoC)?

Thanks :+1: :blush:

**Comment by iteles** [comment]
@RabeaGleissner Still no luck?

**Comment by angiemaguire** [comment]
Hi, @iteles. You should have full access to this now.

**Comment by iteles** [comment]
Great, thanks @angiemaguire !
