### ISSUE TITLE
Add Natalia to London team

### ISSUE THREAD

**Issue by RabeaGleissner** [ladiesofcode/london#31]
Hi @iteles 
Looks like you might have permissions to add another team member to the London team on this repo. I think we should add @nataliaLKB 😄

**Comment by iteles** [comment]
@RabeaGleissner I can, but Angie needs to add her to the organisation first as sadly neither of us have enough permissions for that. Will email!

**Comment by NataliaLKB** [comment]
Thanks @iteles and @RabeaGleissner for taking care of this 👍

**Comment by angiemaguire** [comment]
@NataliaLKB Done :-)

**Comment by angiemaguire** [comment]
@iteles and @RabeaGleissner You should both have permissions to add team members now too.

**Comment by NataliaLKB** [comment]
Wonderful! Thank you @angiemaguire

**Comment by iteles** [comment]
@NataliaLKB Once you accept the invite I can add you to the London team!

@angiemaguire Fantastic, thanks so much 👍
