### ISSUE TITLE
Adding new co-organisers to LoC org and London repo

### ISSUE THREAD

**Issue by iteles** [ladiesofcode/london#33]
@angiemaguire [As you may have seen](https://twitter.com/ladiesofcode/status/748094818597888000), we have been joined by lots of lovely new co-organisers in London :tada:

Would you like to give myself, @RabeaGleissner or @NataliaLKB owner access to the LoC org so we can add them to the org and then the London team or would you like us to pass on the github usernames to you every time we need people added? Please let me know so we can start interacting on GH asap ☺️

**Comment by angiemaguire** [comment]
Hey @iteles just double checked this. You and @rabeagleissner are team maintainers so should be able to add members to the London team. Have a look and let me know.

**Comment by iteles** [comment]
Hey @angiemaguire, thanks for checking. We can add people to the team once they're part of the org, but they need to be invited into org first (by org owners, currently you and @cwaring) before we can add them to the team. 

Let me know how you'd like to play it :+1:

**Comment by angiemaguire** [comment]
My apologies, I've upgraded everyone to team owners so you should be able to add all of the the new organisers.

**Comment by iteles** [comment]
Thanks @angiemaguire, much appreciated ☺️ 
We're looking forward to getting you back in the country and talking about your remote working experiences! #coderlife
