### ISSUE TITLE
Ladies of Code Calendar : September - November

### ISSUE THREAD

**Issue by mongolianprincess** [ladiesofcode/london#36]
## 6th September

**Available Organizers:**
- Inés Pons
- Amy Yang ( can support on day of event)

**Speaker Candidates:**

**Topics:**

**Venue Candidates:**
- Thoughtworks
- Best to email Laura. She is the office manager and has access to the office calendar.
- Please CC in Jade.  She is our contact at Thoughtworks (Natalia and Ines Teles have run at event there before)
## 4th October

**Available Organizers:**
- Natalia
- Amy

**Speaker Candidates:**

**Topics:**

**Venue Candidates:**
[backup] Guardian. Can’t provide food though so we would need a second sponsor
## 1st November

**Available Organizers:**
- Inés Pons
- Natalia

**Speaker Candidates:**
- Claudia Nobrega (Head of Deployments)

**Topics:**
- From Manual Deployments to Continuous Delivery

**Venue Candidates:**
- Ve Interactive (near Farringdon)

**Comment by iteles** [comment]
Hey @mongolianprincess! Not sure where we are with this since my holiday absence but I'm available on 6th September and 1st November too!

**Comment by inespons** [comment]
Hey Ines, 
We decided to deprecate this issue and only maintain the original google doc. We moved the organisation conversation to slack because no one receives the notifications from github anyway. 
I hope you can join ASAP. Let me know if you can't find the invite and I'll try to send it again to you :)

**Comment by RabeaGleissner** [comment]
@mongolianprincess @inespons @iteles Are you happy for me to close the issue?

**Comment by inespons** [comment]
👍 with me
